//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FixMyCar.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using FixMyCar.Entities.Models;
    
    public partial class FixMyCarEntities : DbContext
    {
        public FixMyCarEntities()
            : base("name=FixMyCarEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Customer> Customers { get; set; }
        public DbSet<Repair> Repairs { get; set; }
        public DbSet<RepairDetail> RepairDetails { get; set; }
        public DbSet<RepairDetailLineItem> RepairDetailLineItems { get; set; }
        public DbSet<Vehicle> Vehicles { get; set; }
    }
}
